from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, PageBreak, HRFlowable, KeepTogether
)
from datetime import datetime
import os

# ── COLORS ───────────────────────────────────────────────────
GREEN      = colors.HexColor("#2F8D46")
DARK       = colors.HexColor("#1A1A2E")
LIGHT_GRAY = colors.HexColor("#F5F5F5")
MID_GRAY   = colors.HexColor("#DDDDDD")
DARK_TEXT  = colors.HexColor("#212121")
MUTED      = colors.HexColor("#757575")
CODE_BG    = colors.HexColor("#F8F8F8")


# ── STYLES ───────────────────────────────────────────────────
def make_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="CoverTitle",
        fontSize=30, leading=38,
        textColor=colors.white,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        spaceAfter=10,
    ))
    styles.add(ParagraphStyle(
        name="TopicHeading",
        fontSize=20, leading=26,
        textColor=GREEN,
        fontName="Helvetica-Bold",
        spaceAfter=6,
        spaceBefore=10,
    ))
    styles.add(ParagraphStyle(
        name="ArticleTitle",
        fontSize=15, leading=20,
        textColor=colors.white,
        fontName="Helvetica-Bold",
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="SectionLabel",
        fontSize=8, leading=12,
        textColor=GREEN,
        fontName="Helvetica-Bold",
        spaceBefore=10, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="BodyText2",
        fontSize=10, leading=15,
        textColor=DARK_TEXT,
        fontName="Helvetica",
        alignment=TA_JUSTIFY,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="CodeText",
        fontSize=8, leading=12,
        textColor=colors.HexColor("#C7254E"),
        fontName="Courier",
        leftIndent=10,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="BulletItem",
        fontSize=9, leading=14,
        textColor=DARK_TEXT,
        fontName="Helvetica",
        leftIndent=12,
        spaceAfter=3,
    ))
    styles.add(ParagraphStyle(
        name="TOCTitle",
        fontSize=20, leading=28,
        textColor=DARK_TEXT,
        fontName="Helvetica-Bold",
        spaceAfter=16,
    ))
    styles.add(ParagraphStyle(
        name="TOCTopic",
        fontSize=12, leading=18,
        textColor=GREEN,
        fontName="Helvetica-Bold",
        spaceBefore=10, spaceAfter=4,
        leftIndent=10,
    ))
    styles.add(ParagraphStyle(
        name="TOCEntry",
        fontSize=10, leading=16,
        textColor=DARK_TEXT,
        fontName="Helvetica",
        leftIndent=24,
    ))

    return styles


# ── HEADER & FOOTER ──────────────────────────────────────────
def header_footer(canvas_obj, doc, student_name):
    canvas_obj.saveState()
    w, h = letter

    canvas_obj.setFillColor(GREEN)
    canvas_obj.rect(0, h - 28, w, 28, fill=1, stroke=0)
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont("Helvetica-Bold", 9)
    canvas_obj.drawString(0.5 * inch, h - 18, "GeeksforGeeks Academic Scraper")
    canvas_obj.setFont("Helvetica", 9)
    canvas_obj.drawRightString(w - 0.5 * inch, h - 18, datetime.now().strftime("%B %d, %Y"))

    canvas_obj.setFillColor(LIGHT_GRAY)
    canvas_obj.rect(0, 0, w, 22, fill=1, stroke=0)
    canvas_obj.setFillColor(MUTED)
    canvas_obj.setFont("Helvetica", 7.5)
    canvas_obj.drawString(0.5 * inch, 7, f"Generated by {student_name}")
    canvas_obj.drawCentredString(w / 2, 7, "GFG Learning Module")
    canvas_obj.drawRightString(w - 0.5 * inch, 7, f"Page {doc.page}")

    canvas_obj.restoreState()


# ── DIFFICULTY COLOR ─────────────────────────────────────────
def diff_color(difficulty):
    return {
        "Easy":   colors.HexColor("#2E7D32"),
        "Basic":  colors.HexColor("#2E7D32"),
        "Medium": colors.HexColor("#E65100"),
        "Hard":   colors.HexColor("#B71C1C"),
        "Expert": colors.HexColor("#4A148C"),
    }.get(difficulty, colors.HexColor("#546E7A"))


# ── HELPER ───────────────────────────────────────────────────
def trim(text, max_len=600):
    if not text or text == "Not Available":
        return "Not Available"
    text = str(text)
    return text[:max_len] + ("..." if len(text) > max_len else "")


# ── MAIN FUNCTION ────────────────────────────────────────────
def generate_pdf(data, selected_topics, student_name="Anonymous", filename="GFG_Learning_Module.pdf"):
    styles = make_styles()
    os.makedirs("data", exist_ok=True)
    out_path = os.path.join("data", filename)

    doc = SimpleDocTemplate(
        out_path,
        pagesize=letter,
        leftMargin=0.65 * inch,
        rightMargin=0.65 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.55 * inch,
    )

    def on_page(canvas_obj, doc):
        header_footer(canvas_obj, doc, student_name)

    results = data.get("results", {})
    story = []

    # ── COVER PAGE ───────────────────────────────────────────
    story.append(Spacer(1, 0.5 * inch))

    cover_table = Table(
        [[Paragraph("GFG Learning Module", styles["CoverTitle"])]],
        colWidths=[6.5 * inch]
    )
    cover_table.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), DARK),
        ("TOPPADDING",    (0,0), (-1,-1), 36),
        ("BOTTOMPADDING", (0,0), (-1,-1), 36),
        ("LEFTPADDING",   (0,0), (-1,-1), 30),
        ("RIGHTPADDING",  (0,0), (-1,-1), 30),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 0.2 * inch))

    total_articles = sum(len(results.get(t, [])) for t in selected_topics)

    meta = [
        ["Topics Covered:",   ", ".join(selected_topics)],
        ["Total Articles:",   str(total_articles)],
        ["Date Generated:",   datetime.now().strftime("%B %d, %Y")],
        ["Generated By:",     student_name],
        ["Source:",           "GeeksforGeeks (geeksforgeeks.org)"],
    ]
    meta_table = Table(meta, colWidths=[2 * inch, 4.5 * inch])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",       (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTNAME",       (1,0), (1,-1), "Helvetica"),
        ("FONTSIZE",       (0,0), (-1,-1), 10),
        ("TEXTCOLOR",      (0,0), (0,-1), GREEN),
        ("TEXTCOLOR",      (1,0), (1,-1), DARK_TEXT),
        ("ROWBACKGROUNDS", (0,0), (-1,-1), [colors.white, LIGHT_GRAY]),
        ("TOPPADDING",     (0,0), (-1,-1), 7),
        ("BOTTOMPADDING",  (0,0), (-1,-1), 7),
        ("LEFTPADDING",    (0,0), (-1,-1), 12),
        ("GRID",           (0,0), (-1,-1), 0.5, MID_GRAY),
    ]))
    story.append(meta_table)
    story.append(PageBreak())

    # ── TABLE OF CONTENTS ────────────────────────────────────
    story.append(Paragraph("Table of Contents", styles["TOCTitle"]))
    story.append(HRFlowable(width="100%", thickness=2, color=GREEN, spaceAfter=12))

    for topic in selected_topics:
        articles = results.get(topic, [])
        story.append(Paragraph(f"📂 {topic}", styles["TOCTopic"]))
        for i, art in enumerate(articles, 1):
            story.append(Paragraph(
                f"{i}. {art.get('title', 'Untitled')}",
                styles["TOCEntry"]
            ))

    story.append(PageBreak())

    # ── ARTICLE PAGES ────────────────────────────────────────
    for topic in selected_topics:                                          # ← level 1
        articles = results.get(topic, [])
        if not articles:
            continue

        # Topic divider page
        topic_table = Table(
            [[Paragraph(topic, styles["CoverTitle"])]],
            colWidths=[6.5 * inch]
        )
        topic_table.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), DARK),
            ("TOPPADDING",    (0,0), (-1,-1), 20),
            ("BOTTOMPADDING", (0,0), (-1,-1), 20),
            ("LEFTPADDING",   (0,0), (-1,-1), 20),
        ]))
        story.append(topic_table)
        story.append(PageBreak())

        # Sort articles Easy → Medium → Hard
        difficulty_order = {"Easy": 1, "Basic": 1, "Medium": 2, "Hard": 3, "Expert": 4, "Not Available": 5}
        articles = sorted(articles, key=lambda a: difficulty_order.get(a.get("difficulty", "Not Available"), 5))

        for idx, art in enumerate(articles, 1):                           # ← level 2
            title      = art.get("title", "Untitled")
            difficulty = art.get("difficulty", "Not Available")
            concepts   = art.get("concepts", "Not Available")
            snippets   = art.get("code_snippets", ["Not Available"])
            complexity = art.get("complexity", ["Not Available"])
            related    = art.get("related_links", [])
            url        = art.get("url", "")
            dc         = diff_color(difficulty)

            # Article header
            header = Table(
                [[
                    Paragraph(f"#{idx:02d}  {title}", styles["ArticleTitle"]),
                    Paragraph(difficulty, ParagraphStyle(
                        "db", fontSize=9, fontName="Helvetica-Bold",
                        textColor=colors.white, alignment=TA_CENTER, leading=12
                    )),
                ]],
                colWidths=[5.5*inch, 1.0*inch]
            )
            header.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), DARK),
                ("BACKGROUND",    (1,0), (1,0),   dc),
                ("TOPPADDING",    (0,0), (-1,-1), 14),
                ("BOTTOMPADDING", (0,0), (-1,-1), 14),
                ("LEFTPADDING",   (0,0), (0,0),   16),
                ("RIGHTPADDING",  (0,0), (-1,-1), 10),
                ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
            ]))
            story.append(KeepTogether([header, Spacer(1, 8)]))

            # Source URL
            story.append(Paragraph(
                f"Source: {url}",
                ParagraphStyle("url", fontSize=8, textColor=MUTED, fontName="Helvetica", spaceAfter=10)
            ))

            # 1. Key Concepts
            story.append(Paragraph("KEY TECHNICAL CONCEPTS", styles["SectionLabel"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=5))
            story.append(Paragraph(trim(concepts, 700), styles["BodyText2"]))

            # 2. Code Snippets
            story.append(Paragraph("CODE SNIPPETS / IMPLEMENTATION", styles["SectionLabel"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=5))
            valid_snippets = [s for s in snippets if s and s != "Not Available"]
            if valid_snippets:
                for snippet in valid_snippets[:2]:
                    safe = snippet.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
                    lines = safe.split("\n")[:18]
                    code_block = Table(
                        [[Paragraph("<br/>".join(lines), styles["CodeText"])]],
                        colWidths=[6.5 * inch]
                    )
                    code_block.setStyle(TableStyle([
                        ("BACKGROUND",    (0,0), (-1,-1), CODE_BG),
                        ("BOX",           (0,0), (-1,-1), 0.5, MID_GRAY),
                        ("LEFTPADDING",   (0,0), (-1,-1), 12),
                        ("RIGHTPADDING",  (0,0), (-1,-1), 12),
                        ("TOPPADDING",    (0,0), (-1,-1), 8),
                        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                    ]))
                    story.append(code_block)
                    story.append(Spacer(1, 5))
            else:
                story.append(Paragraph("Not Available", styles["BodyText2"]))

            # 3. Complexity
            story.append(Paragraph("COMPLEXITY ANALYSIS", styles["SectionLabel"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=5))
            valid_cx = [c for c in complexity if c and c != "Not Available"]
            if valid_cx:
                for c in valid_cx[:4]:
                    story.append(Paragraph(f"• {trim(c, 200)}", styles["BulletItem"]))
            else:
                story.append(Paragraph("Not Available", styles["BodyText2"]))

            # 4. Related Links
            story.append(Paragraph("REFERENCES / RELATED LINKS", styles["SectionLabel"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=5))
            valid_links = [r for r in related if r.get("title") and r["title"] != "Not Available"]
            if valid_links:
                for link in valid_links[:5]:
                    story.append(Paragraph(
                        f"• {trim(link.get('title',''), 80)} — {link.get('url','')}",
                        styles["BulletItem"]
                    ))
            else:
                story.append(Paragraph("Not Available", styles["BodyText2"]))

            # Divider between articles (no forced page break)
            story.append(Spacer(1, 0.3 * inch))
            story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=10))

        story.append(PageBreak())                                          # ← page break between TOPICS only

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return out_path